name: RNA-Seq-analysis
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake=5.3.0
  - graphviz=2.40.1
# command tool installs
  - R=3.5.1
  - python=3.6.7
# bioconda channel installs
  - multiqc=1.5
  - hisat2=2.1.0
  - samtools=1.9
  - subread=1.6.4  # featureCounts included
  - htseq=0.11.2  # htseq-count included
  - r-yaml=2.2.0
  - bioconductor-edger=3.26.0
  - r-statmod=1.4.30
  - qualimap=2.2.2a
